services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"


  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./chroma_data:/chroma/chroma


  django:
    build: .
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - chromadb


  celery:
    build: .
    command: celery -A config worker -l info
    env_file:
      - ./backend/.env
    depends_on:
      - redis


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./nginx:/etc/nginx/conf.d
