# Generated by Django 6.0.3 on 2026-03-30 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('edge_tts', 'Edge TTS'), ('xtts_v2', 'XTTS v2 (Voice Clone)')], default='edge_tts', max_length=20)),
                ('edge_voice_name', models.CharField(default='en-US-AriaNeural', max_length=100)),
                ('edge_rate', models.CharField(default='+0%', max_length=20)),
                ('edge_volume', models.CharField(default='+0%', max_length=20)),
                ('xtts_speaker_embedding_path', models.CharField(blank=True, default='', max_length=500)),
                ('xtts_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceCloneJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('reference_audio_path', models.CharField(max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('voice_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clone_jobs', to='voice.voiceprofile')),
            ],
        ),
    ]
